### ISSUE TITLE
Changelog on wiki is missing versions since 0.9.3

### ISSUE THREAD

**Issue by edmorley** [seb-m/pyinotify#103]
The most recent version listed on the changelog here is v0.9.3:
https://github.com/seb-m/pyinotify/wiki/Recent-Developments
...whereas the newest release is v0.9.6.

Also, this page wasn't very easy to find - would it be possible to link to it (if it's the canonical changelog) from the readme and/or the pypi page, using the phrase "changelog" or "release notes"? ("Recent developments" doesn't immediately mean the same thing to me).

Many thanks! :-)

**Comment by alexkiro** [comment]
+1 for this.
