### ISSUE TITLE
Does it work on Mac?

### ISSUE THREAD

**Issue by simontorres** [seb-m/pyinotify#170]
Sorry for the intrusion, I'm developing a software which is going to work on Linux but eventually it might be required to work on Mac (and be portable, and all that stuff).

The docs says it is made for Linux, does anyone have any information about getting it work on mac or any plans.

Thanks

**Comment by asenov** [comment]
This is a pure Linux feature 
https://en.wikipedia.org/wiki/Inotify
Inotify (inode notify) is a Linux kernel subsystem that acts to extend filesystems to notice changes to the filesystem, and report those changes to applications. It replaces an earlier facility, dnotify, which had similar goals.

**Comment by simontorres** [comment]
Thanks!
