### ISSUE TITLE
Linux 3.4 - Bindings Error

### ISSUE THREAD

**Issue by niallfleming** [seb-m/pyinotify#41]
3.4.6 and 3.4.7 Kernel compiled with the same config as my 2.6.32 that works.

CONFIG_FSNOTIFY=y
CONFIG_DNOTIFY=y
CONFIG_INOTIFY_USER=y

Both give the following error:

InotifyBindingNotFoundError: Couldn't find any inotify binding

Any clues?

**Comment by stefanct** [comment]
I ran into missing ctypes today. It would be nice if the InotifyBindingNotFoundError exception would indicate what's actually the problem. Users of the library usually simply print the exception message and let the program user figure the problem out themselves. That's what fail2ban does and it would be way easier if the exception text would at least indicate which imports have been tried and did(n't) work.

Without this issue it would have taken me way longer to figure it out, thanks for reporting (and replying ofc :)
