### ISSUE TITLE
sysctl setting fails on x86_64

### ISSUE THREAD

**Issue by grubberr** [seb-m/pyinotify#84]
I have downloaded the latest version of pyinotify.py from github
and run such script:

```
#!/usr/bin/python

import pyinotify
pyinotify.max_queued_events.value = 32768
```

on 32bit centos 6.5 it works OK
on 64bit centos 6.5 it fails with

```
Traceback (most recent call last):
  File "./t.py", line 5, in <module>
    pyinotify.max_queued_events.value = 32768
  File "/root/pyinotify.py", line 354, in set_val
    self._inotify_wrapper.str_errno())
OSError: [Errno 14] Errno=Bad address (EFAULT)

**Comment by blueyed** [comment]
This applies to reading the values, too.
At least it fails for me already (Linux 3.13.0-46-generic, Ubuntu 14.04, 64bit).
