### ISSUE TITLE
0.9.5 release

### ISSUE THREAD

**Issue by szepeviktor** [seb-m/pyinotify#90]
Do you see the release date of 0.9.5?

**Comment by seb-m** [comment]
Hello Viktor,

Now that you ask I realize that's a bit of time since a new version didn't get formally released. I shall correct that soon. Thank you for the reminder.

**Comment by kYroL01** [comment]
Just realize of new release now! Thank you!

**Comment by seb-m** [comment]
Released! f3ee9bb651654930f034d6001ffa9ba5f5c43b3d

**Comment by szepeviktor** [comment]
I thought it wouldn't be this EZ.

**Comment by szepeviktor** [comment]
Thank you!!
