### ISSUE TITLE
Loop stops when tries to call cleanup method

### ISSUE THREAD

**Issue by alasarr** [seb-m/pyinotify#98]
Hi,
After several hours running pynotify watching a folder, It suddenly stops with the following stacktrace.

```
File "/app/meteo/filechangeswatcher.py", line 46, in run
    self.notifier.loop()
  File "/usr/local/lib/python2.7/dist-packages/pyinotify.py", line 1424, in loop
    self.process_events()
  File "/usr/local/lib/python2.7/dist-packages/pyinotify.py", line 1322, in process_events
    self._sys_proc_fun.cleanup()  # remove olds MOVED_* events records
AttributeError: 'NoneType' object has no attribute 'cleanup'
```
I'm listening to the following events: *pyinotify.IN_CLOSE_WRITE|pyinotify.IN_CREATE|pyinotify.IN_MOVED_TO*. 

My process handler looks like:

```

class EventHandler(pyinotify.ProcessEvent):
    
    def  __init__(self,conn,logger): 
        pyinotify.ProcessEvent.__init__(self)
        // something here....

    def process_IN_CLOSE_WRITE(self, event):
        self.__process(event.pathname)

    def process_IN_CREATE(self, event):
        self.__process(event.pathname)

    def process_IN_MOVED_TO(self, event):
        self.__process(event.pathname)

    def __process(self, f_abspath):
          // something here
```

**Comment by seb-m** [comment]
Hi, can't help you much but a couple of observations:

1. Even if it is probably unrelated to your issue you should not call the constructor of `ProcessEvent`directly [see this comment](https://github.com/seb-m/pyinotify/blob/master/python2/pyinotify.py#L900) for an alternative.
2. From your stack trace, the only way `_sys_proc_fun` could be `None` is if the method [stop()](https://github.com/seb-m/pyinotify/blob/master/python2/pyinotify.py#L1439) got called previously. I'm not sure why but it seems to process events after it is stopped and it shouldn't happen.

**Comment by seb-m** [comment]
Closing, feel free to reopen it if you have more details.

**Comment by alasarr** [comment]
Sorry, I completely forgot to answer. You were right I was calling to stop by accident.

**Comment by Burrito-Bazooka** [comment]
> [...] the only way `_sys_proc_fun` could be `None` is if the method [stop()](https://github.com/seb-m/pyinotify/blob/master/python2/pyinotify.py#L1439) got called previously. I'm not sure why but it seems to process events after it is stopped and it shouldn't happen.

Seems to be the case for me too, using the package from PyPI. Should this not be a separate issue/bug report? I don't think I'm familiar enough with the code to fix it myself.
